services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    restart: unless-stopped
    networks:
      - frontend
    labels: # container_name defines subdomain
      - "traefik.enable=true"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"

networks:
  frontend:
    external: true
