version: 2
updates:
  # Check compose.yaml image tags across all services/<servicename> folders
  - package-ecosystem: "docker-compose"
    directories:
      - "/services/*"
    schedule:
      interval: "daily"
# default cooldown is now set to 3 days. (Keeping this since I might change it later)
#      cooldown:
#      default-days: 3

    groups:
      stacks:
        patterns: # Since each service is each own context * will group by directory
         - "*"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "Dependencies:"