[homelab]
192.168.31.50 ansible_user=simon

[digital_ocean]
# I currently dont have any digitalocean servers so this is blank on purpose

[digital_ocean:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_user=root

[homelab:vars]
ansible_user=simon
ansible_ssh_private_key_file=~/.ssh/id_ed25519_sk