---
- name: Update Debian 13 servers
  hosts: homelab
  become: true
  gather_facts: false
  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: "full"
        autoremove: true
        autoclean: true
